### PR TITLE
Bugfix for Blank node ordering, RDF lists and DecimalFormat

### LINKED ISSUE #8: Serialization order with blank nodes is non-deterministic
This issue was originally reported here:
* https://github.com/atextor/owl-cli/issues/8

When multiple statements share the same subject and predicate and their objects are blank nodes, the serialization order is non-deterministic. Although they are sorted ([cf. code](https://github.com/atextor/turtle-formatter/blob/47adb1ce83717f5e218136f0eba3f36ac2dbf71f/src/main/java/de/atextor/turtle/formatter/TurtleFormatter.java#L596)) the reason could be that the lexicographic order of blank node ids varies between runs due to Jena's parser logic, i.e. blank node ids are already nondeterministic.
Solutions include:
* Implement own parser (see also #2)
* Don't use blank node ids for sorting. Instead, sort by a hash over the statements that have the blank node as subject.

### LINKED ISSUE #13: Formatting RDF Lists results in invalid output
Using default style, 

```
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix qudt: <http://qudt.org/schema/qudt/> .
@prefix sh: <http://www.w3.org/ns/shacl#> .

qudt:IntegerUnionList
  a rdf:List ;
  rdf:first [
      sh:datatype xsd:nonNegativeInteger ;
    ] ;
  rdf:rest (
      [
        sh:datatype xsd:positiveInteger ;
      ]
      [
        sh:datatype xsd:integer ;
      ]
    ) ;
  rdfs:label "Integer union list" ;
.
```
is transformed to 
```
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix qudt: <http://qudt.org/schema/qudt/> .
@prefix sh: <http://www.w3.org/ns/shacl#> .

 ( [
  sh:datatype xsd:nonNegativeInteger ;
] [
  sh:datatype xsd:positiveInteger ;
] [
  sh:datatype xsd:integer ;
] ) a rdf:List ;
  rdfs:label "Integer union list" ;
  rdf:first;
  rdf:rest ( ) .
```

which is not only wrong but also not valid TTL anymore.

### LINKED ISSUE #14: Formatting result is platform-dependent
On my machine (DE settings), the 'LiteralTest' fails:

All I can see is that `4.2E9` and `4,2E9` differ - seems to be a platform-dependent formatting issue

```
org.opentest4j.AssertionFailedError: 
expected: "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix : <http://example.com/> .

:foo01 :bar 1 .

:foo02 :bar "2" .

:foo03 :bar true .

:foo04 :bar -5.0 .

:foo05 :bar 4.2E9 .

:foo06 :bar "2021-01-01"^^xsd:date .

:foo07 :bar "something"^^:custom .

:foo08 :bar "something"@en .

:foo09 :bar "This contains a \" quote" .

:foo10 :bar """This contains a
linebreak""" ."
 but was: "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix : <http://example.com/> .

:foo01 :bar 1 .

:foo02 :bar "2" .

:foo03 :bar true .

:foo04 :bar -5.0 .

:foo05 :bar 4,2E9 .

:foo06 :bar "2021-01-01"^^xsd:date .

:foo07 :bar "something"^^:custom .

:foo08 :bar "something"@en .

:foo09 :bar "This contains a \" quote" .

:foo10 :bar """This contains a
linebreak""" ."
	at java.base@21.0.1/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base@21.0.1/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at app//de.atextor.turtle.formatter.TurtleFormatterTest.testLiterals(TurtleFormatterTest.java:125)
	at java.base@21.0.1/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base@21.0.1/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base@21.0.1/java.util.ArrayList.forEach(ArrayList.java:1596)
```

### PR DESCRIPTION
**Pull request by fkleedorfer**
fixes #13 - A quick fix. The writeListResource method was not handling non-blank nodes properly

fixes #14 - Another quick fix, setting the locale to US

fixes #8 (!) - Not so quick. After some tinkering I found out that neither model nor graph retain any actually useful information about (blank) node ordering, but it's actually quite simple to intercept the parsing code and just keep track of newly created blank nodes during RDF parsing, which gives you their ordering. At the same time, I found out that you can also grab any labels. **However**, this requires formatting the RDF string representation, not the model, so the `TurtleFormatter.apply(Model)` will not give you preservation of blank node ordering (and the `accept(Model, OutputStream)` method won't either).

In while fixing #8 I found a few other bugs related to blank nodes :
- handling of cycles 
- when blank nodes need to be labeled (more than one incoming arcs or part of a blank node cycle, but in each cycle, only one needs to be labeled)

Oh and it may be able to address #2, at least partly, based on the approach introduced here.

EDIT: a blank node cycle is e.g.:
```
_:a :has _:b .
_:b :has _:a .
```

### CODE REVIEW

**Comment by fkleedorfer** [comment]
There is still a bug in there regarding blank node labeling, commit coming up

**Comment by fkleedorfer** [comment]
@atextor Being new to gradle, I did not see an option to format the source code (ironically ;-). Is there any build target for formatting?

**Comment by fkleedorfer** [comment]
@atextor I understand this is quite an intrusive PR - I tried to minimize that but it comes with the territory. 

In that vein, two more refactorings that I'm planning now :
- put the BlankNodeMetadata into the State (so we don't clutter the method signatures with it)
- change the ComparableRDFNodeFactory such that it returns a comparator, not a Comparable, so that we don't create a new Object for each comparison

**Comment by fkleedorfer** [comment]
I think this is ready to merge. 

I would appreciate publication to maven central soon, so I can then finish the contribution of the RDF format to [spotless](https://github.com/diffplug/spotless/), which uses turtle-formatter for TTL

**Comment by atextor** [comment]
Hi @fkleedorfer,
first of all, thank you very much for your contribution! :fireworks:

> @atextor Being new to gradle, I did not see an option to format the source code (ironically ;-). Is there any build target for formatting?

Unfortunately there is no such thing with the project being mostly a small one-person project (until now that is :-)). I have created issue #25 to document/check/automate this. There is a plan to (1) turn the [owl-cli project into a Maven project](https://github.com/atextor/owl-cli/issues/19) and (2) [merge the turtle-formatter project into owl-cli](https://github.com/atextor/owl-cli/issues/20), this would enable usage of e.g. the [formatter-maven-plugin](https://code.revelc.net/formatter-maven-plugin/). I think this is along the lines of what you have in mind. For now, I'd just ignore formatting issues in your PR and fix it manually subsequently.

> @atextor I understand this is quite an intrusive PR - I tried to minimize that but it comes with the territory.

I was aware that is no small fix when creating issue #8, so no problem from my side. I'd rather compliment you on going all the way of fixing it, even when it turned out to be no small thing.

> I think this is ready to merge.

In https://github.com/atextor/turtle-formatter/issues/8#issuecomment-2339665847 you mention checking for collisions with other generated blank node labels, is this already addressed?

> I would appreciate publication to maven central soon, so I can then finish the contribution of the RDF format to [spotless](https://github.com/diffplug/spotless/), which uses turtle-formatter for TTL

I'm happy to do a release as soon as the PR is merged.

One more thing: I you like, please feel free to add yourself to the CONTRIBUTORS file (need to pull main first, I just created it).

File: src/main/java/de/atextor/turtle/formatter/TurtleFormatter.java [hunk 1]
```diff
@@ -1,19 +1,14 @@
...
 import org.apache.jena.irix.IRIException;
-import org.apache.jena.rdf.model.Literal;
-import org.apache.jena.rdf.model.Model;
-import org.apache.jena.rdf.model.Property;
-import org.apache.jena.rdf.model.RDFList;
-import org.apache.jena.rdf.model.RDFNode;
-import org.apache.jena.rdf.model.Resource;
-import org.apache.jena.rdf.model.ResourceFactory;
-import org.apache.jena.rdf.model.Statement;
+import org.apache.jena.rdf.model.*;
```
Comment (atextor) [inline src/main/java/de/atextor/turtle/formatter/TurtleFormatter.java:11]: Please remove wildcard import.

File: src/main/java/de/atextor/turtle/formatter/TurtleFormatter.java [hunk 2]
```diff
@@ -29,19 +24,15 @@
...
 import java.io.OutputStream;
 import java.nio.charset.StandardCharsets;
-import java.util.Comparator;
-import java.util.HashMap;
-import java.util.HashSet;
-import java.util.List;
-import java.util.Map;
-import java.util.Optional;
-import java.util.Set;
+import java.util.*;
```
Comment (atextor) [inline src/main/java/de/atextor/turtle/formatter/TurtleFormatter.java:27]: Please remove wildcard import.

File: src/main/java/de/atextor/turtle/formatter/TurtleFormatter.java [hunk 3]
```diff
@@ -121,6 +112,24 @@ public String apply( final Model model ) {
         return outputStream.toString();
     }
 
+    public String applyToContent( final String content ) {
```
Comment (atextor) [inline src/main/java/de/atextor/turtle/formatter/TurtleFormatter.java:115]: This method should have a JavaDoc, that specifically clarifies that the content String is supposed to contain a valid RDF/Turtle document.

File: src/main/java/de/atextor/turtle/formatter/FormattingStyle.java [hunk 4]
```diff
@@ -210,7 +212,7 @@ public class FormattingStyle {
     );
 
     @Builder.Default
-    public BiFunction<Resource, Integer, String> anonymousNodeIdGenerator = ( resource, integer ) -> "_:gen" + integer;
+    public BiFunction<Resource, Integer, String> anonymousNodeIdGenerator = ( resource, integer ) -> "gen" + integer;
```
Comment (atextor) [inline src/main/java/de/atextor/turtle/formatter/FormattingStyle.java:215]: This is a good change. Please also update in the README the default value of the description for `anonymousNodeIdGenerator` (where the `_:` is still included).

File: src/main/java/de/atextor/turtle/formatter/TurtleFormatter.java [hunk 5]
```diff
@@ -222,18 +244,63 @@ private State buildInitialState( final Model model, final OutputStream outputStr
...
+        candidatesInOrder.addAll(
+                        new ArrayList<>(currentState.getBlankNodeMetadata().getLabeledBlankNodes())
+                        .stream()
+                        .sorted( currentState.getRDFNodeComparatorFactory().comparator())
+                        .toList());
+        candidatesInOrder.addAll(
+                        candidates
+                        .stream()
+                        .sorted( currentState.getRDFNodeComparatorFactory().comparator())
+                        .toList());
```
Comment (atextor) [inline src/main/java/de/atextor/turtle/formatter/TurtleFormatter.java:269]: Can this be simplified to the following?

```java
List<Resource> candidatesInOrder = Streams.concat(
     currentState.getBlankNodeMetadata().getLabeledBlankNodes().stream()
       .sorted( currentState.getRDFNodeComparatorFactory().comparator() ),
     candidates.stream()
       .sorted( currentState.getRDFNodeComparatorFactory().comparator() ) )
  .toList();
```

File: src/main/java/de/atextor/turtle/formatter/blanknode/BlankNodeOrderAwareTurtleParser.java [hunk 6]
```diff
@@ -0,0 +1,104 @@
+package de.atextor.turtle.formatter.blanknode;
+
+import org.apache.jena.atlas.web.ContentType;
+import org.apache.jena.graph.Graph;
+import org.apache.jena.graph.Node;
+import org.apache.jena.rdf.model.Model;
+import org.apache.jena.rdf.model.ModelFactory;
+import org.apache.jena.riot.*;
```
Comment (atextor) [inline src/main/java/de/atextor/turtle/formatter/blanknode/BlankNodeOrderAwareTurtleParser.java:8]: Please remove wildcard import.

File: src/test/java/de/atextor/turtle/formatter/TurtleFormatterTest.java [hunk 7]
```diff
@@ -719,6 +737,301 @@ void testRdfTypeAsObjectIsValid() {
...
+             ].""";
+        String expected = """
+          @prefix ex: <http://example.com/ns#> .
+           
+          _:gen0 ex:has [ 
+              ex:has _:gen0 ;
+            ] .""";
+        final FormattingStyle style = FormattingStyle.DEFAULT;
+        final TurtleFormatter formatter = new TurtleFormatter( style );
+        for (int i = 0; i < 20; i++) {
```
Comment (atextor) [inline src/test/java/de/atextor/turtle/formatter/TurtleFormatterTest.java:848]: I see what you're doing here but I wonder if it's necessary _or_ sufficient. It might be a good idea to turn this logic into proper property-based tests in the [jqwik](https://jqwik.net/)-based TurtleFormatterPropertyTest.java, but you can consider this out of scope for this PR.

**Review by atextor — CHANGES_REQUESTED** [review]

**Comment by atextor** [comment]
Please edit the PR description so that it does not contain "fix #2" any more, because that would lead to GH automatically closing that issue with this PR, which is not what we want (since it's only one step towards the solution).

File: src/test/java/de/atextor/turtle/formatter/TurtleFormatterTest.java (hunk 7 above)
Comment (fkleedorfer) [reply src/test/java/de/atextor/turtle/formatter/TurtleFormatterTest.java:848]: I'll leave it as-is then (for this PR anyway). These loops were necessary (and sufficient) while implementing the constant blank node serialization code: it seems the probability for different ordering over the runs are uniformly distributed.

File: src/main/java/de/atextor/turtle/formatter/blanknode/BlankNodeOrderAwareTurtleParser.java (hunk 6 above)
Comment (fkleedorfer) [reply src/main/java/de/atextor/turtle/formatter/blanknode/BlankNodeOrderAwareTurtleParser.java]: done

File: src/main/java/de/atextor/turtle/formatter/TurtleFormatter.java (hunk 5 above)
Comment (fkleedorfer) [reply src/main/java/de/atextor/turtle/formatter/TurtleFormatter.java]: done

File: src/main/java/de/atextor/turtle/formatter/TurtleFormatter.java (hunk 3 above)
Comment (fkleedorfer) [reply src/main/java/de/atextor/turtle/formatter/TurtleFormatter.java:143]: added comments to all 3 public methods

File: src/main/java/de/atextor/turtle/formatter/TurtleFormatter.java (hunk 2 above)
Comment (fkleedorfer) [reply src/main/java/de/atextor/turtle/formatter/TurtleFormatter.java]: done

File: src/main/java/de/atextor/turtle/formatter/TurtleFormatter.java (hunk 1 above)
Comment (fkleedorfer) [reply src/main/java/de/atextor/turtle/formatter/TurtleFormatter.java]: done

**Comment by fkleedorfer** [comment]
ready

**Comment by fkleedorfer** [comment]
(really ready)

**Comment by fkleedorfer** [comment]
> There is a plan to (1) turn the https://github.com/atextor/owl-cli/issues/19 and (2) https://github.com/atextor/owl-cli/issues/20, this would enable usage of e.g. the [formatter-maven-plugin](https://code.revelc.net/formatter-maven-plugin/).There is a plan to (1) turn the https://github.com/atextor/owl-cli/issues/19 and (2) https://github.com/atextor/owl-cli/issues/20, this would enable usage of e.g. the [formatter-maven-plugin](https://code.revelc.net/formatter-maven-plugin/).

Have you looked into writing a plugin for the formatter-maven-plugin? I chose spotless because we already use it. It's not entirely straightforward to contribute a language, though. Allows for maven, gradle and sbt support if you can pull it off, which is nice.

**Comment by atextor** [comment]
> > There is a plan to (1) turn the [atextor/owl-cli#19](https://github.com/atextor/owl-cli/issues/19) and (2) [atextor/owl-cli#20](https://github.com/atextor/owl-cli/issues/20), this would enable usage of e.g. the [formatter-maven-plugin](https://code.revelc.net/formatter-maven-plugin/).There is a plan to (1) turn the [atextor/owl-cli#19](https://github.com/atextor/owl-cli/issues/19) and (2) [atextor/owl-cli#20](https://github.com/atextor/owl-cli/issues/20), this would enable usage of e.g. the [formatter-maven-plugin](https://code.revelc.net/formatter-maven-plugin/).
> 
> Have you looked into writing a plugin for the formatter-maven-plugin? I chose spotless because we already use it. It's not entirely straightforward to contribute a language, though. Allows for maven, gradle and sbt support if you can pull it off, which is nice.

I was only talking about using the formatter-maven-plugin to format the Java code, to make contributions like yours more convenient. I've not looked into enhancing it to support Turtle.

**Review by atextor — CHANGES_REQUESTED** [review]

**Comment by fkleedorfer** [comment]
> I was only talking about using the formatter-maven-plugin to format the Java code, to make contributions like yours more convenient. I've not looked into enhancing it to support Turtle.

The spotless project provide java formatting for gradle as well. Might be worth looking into.

**Review by atextor — APPROVED** [review]
